// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7grg_YNz75keWJ617LbOTngFGh1q_1Nc',
    appId: '1:267943043201:web:11d04ba22964bfb9ffad80',
    messagingSenderId: '267943043201',
    projectId: 'renui-app',
    authDomain: 'renui-app.firebaseapp.com',
    storageBucket: 'renui-app.firebasestorage.app',
    measurementId: 'G-59WCF8BRQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5CMiJFrhL4mkKvGzYu7KJLJmEVh-PoP4',
    appId: '1:267943043201:android:f965b0f5407f2801ffad80',
    messagingSenderId: '267943043201',
    projectId: 'renui-app',
    storageBucket: 'renui-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7grg_YNz75keWJ617LbOTngFGh1q_1Nc',
    appId: '1:267943043201:web:ba453e47341eb78affad80',
    messagingSenderId: '267943043201',
    projectId: 'renui-app',
    authDomain: 'renui-app.firebaseapp.com',
    storageBucket: 'renui-app.firebasestorage.app',
    measurementId: 'G-XTGFPTB4LJ',
  );
}
