// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqYk26Hr4tjqKKrh4-qodrC1A0pNMfvCs',
    appId: '1:101583822303:web:b1863acee2ca4a1030f86a',
    messagingSenderId: '101583822303',
    projectId: 'reuni-app-b2463',
    authDomain: 'reuni-app-b2463.firebaseapp.com',
    storageBucket: 'reuni-app-b2463.firebasestorage.app',
    measurementId: 'G-1HYK008JGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdVTwRlCGVsMbMwuhqdf-olNfgXEzwas',
    appId: '1:101583822303:android:cd5a14f86e34d00a30f86a',
    messagingSenderId: '101583822303',
    projectId: 'reuni-app-b2463',
    storageBucket: 'reuni-app-b2463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQfeag4JKxECiBXStzmpoBw03weB8HUeA',
    appId: '1:101583822303:ios:71f2400f3c87a08e30f86a',
    messagingSenderId: '101583822303',
    projectId: 'reuni-app-b2463',
    storageBucket: 'reuni-app-b2463.firebasestorage.app',
    iosBundleId: 'com.example.reuni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQfeag4JKxECiBXStzmpoBw03weB8HUeA',
    appId: '1:101583822303:ios:71f2400f3c87a08e30f86a',
    messagingSenderId: '101583822303',
    projectId: 'reuni-app-b2463',
    storageBucket: 'reuni-app-b2463.firebasestorage.app',
    iosBundleId: 'com.example.reuni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqYk26Hr4tjqKKrh4-qodrC1A0pNMfvCs',
    appId: '1:101583822303:web:559d8d25df2c982430f86a',
    messagingSenderId: '101583822303',
    projectId: 'reuni-app-b2463',
    authDomain: 'reuni-app-b2463.firebaseapp.com',
    storageBucket: 'reuni-app-b2463.firebasestorage.app',
    measurementId: 'G-NJ03HBT167',
  );
}
